root: true
env:
  es2022: true
  node: true
parserOptions:
  ecmaVersion: 13
  sourceType: module
extends:
  - xo
  - plugin:unicorn/recommended
rules:
  indent: [error, tab]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi:  [error, never]
  semi-spacing:
    - error
    -
      before: false
      after: true
  no-debugger: off
  no-console: off
  no-template-curly-in-string: off
  no-unused-expressions:
    - error
    -
      allowShortCircuit: true
      allowTernary: true
      allowTaggedTemplates: true
  camelcase: off
  capitalized-comments: off
  spaced-comment: off
  padding-line-between-statements: off
  no-new-func: off
  unicorn/filename-case: off
  unicorn/prevent-abbreviations: off
  unicorn/no-reduce: off
  unicorn/no-array-reduce: off
  unicorn/consistent-function-scoping: off
  # unicorn/no-abusive-eslint-disable: off
  # Bug no ctx.body Koa
  require-atomic-updates: off
